title: 我的技術筆記
description: "Laravel / JS / DevOps 筆記"
url: "https://aul11cat.github.io"   # ← 改成你的 GitHub Pages 網址
baseurl: ""                         # 若放子資料夾才設定
repository: "aul11cat/aul11cat.github.io"

remote_theme: "mmistakes/minimal-mistakes"

# 文章網址結構
permalink: /:categories/:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

paginate: 10

author:
  name   : "你的名字"
  avatar : "/assets/images/avatar.png"
  bio    : "後端工程師，Laravel / JS / 投資"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/yourname"

# 導覽列
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
